### ISSUE TITLE
 Button Remapping is greyed out/not functional

### ISSUE THREAD

**Issue by ifighftdragons** [opengateware/arcade-irem_m92#2]
### Version (or build number)

0.1.0

### Actual Behavior

Button Remapping is greyed out/not functional

**Comment by boogermann** [comment]
I suspect there might be a bug with the Pocket firmware, as the option will be available randomly even though all the files are in the proper place, sometimes swapping games will magically activate it. This still needs to be investigated

**Comment by boogermann** [comment]
@ifighftdragons can you please manually update the `input.json` file inside `Cores\opengateware.irem_m92` to
```json
{
    "input": {
        "magic": "APF_VER_1",
        "controllers": [
            {
                "type": "default",
                "mappings": []
            }
        ]
    }
}
```
This is fixed and will be available on the next release

**Comment by ifighftdragons** [comment]
> @ifighftdragons can you please manually update the `input.json` file inside `Cores\opengateware.irem_m92` to
> 
> ```json
> {
>     "input": {
>         "magic": "APF_VER_1",
>         "controllers": [
>             {
>                 "type": "default",
>                 "mappings": []
>             }
>         ]
>     }
> }
> ```
> 
> This is fixed and will be available on the next release

Tried this just now. It makes the option not greyed out anymore, but it's sti,, impossible to go into the settings to change the button mappings. Trying to enter into the button settings menu doesn't work.

**Comment by ifighftdragons** [comment]
This will fix it:

{
"input":{
"magic": "APF_VER_1",
"controllers": [
{
"type": "default",
"mappings": []
}
]
}
}
