### ISSUE TITLE
Core sorted as "Arcade" instead of "Arcade Multi"

### ISSUE THREAD

**Issue by lunchpacked130** [opengateware/arcade-irem_m92#7]
### Version (or build number)

0.1.1

### Steps to reproduce

Open Openfpga Menu

find Irem-M92 core in "Arcade" folder

### Expected Behavior

Open Openfpga Menu

find Irem-M92 core in "Arcade Multi" folder

### Actual Behavior

N/A

### Additional Context

Can be changed by manually editing platform json.

Core is a Multi Arcade system and should be sorted as such

**Comment by davewongillies** [comment]
This is fixed in the version 0.1.1

https://github.com/opengateware/arcade-irem_m92/blob/0.1.1/pkg/pocket/Platforms/irem_m92.json#L3
